services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto
    restart: unless-stopped
    # Volumes opcionais (descomente se quiser desenvolvimento ao vivo)
    # volumes:
    #  - ./MVC_sistema_leitura_hidrometros:/app/MVC_sistema_leitura_hidrometros

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
# Arquivo adaptado para remover backend Node legado e adicionar serviço Flask
