services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file: .env
    environment:
      - DEBUG_AUTH=1
      - AUTO_MIGRATE=1
      - DEFAULT_DEVICE_SERIAL=SIMULADOR001
      - DEFAULT_DEVICE_CLIENT_ID=1
    depends_on:
      - mosquitto
      - postgres
    ports:
      - "5000:5000"
    restart: unless-stopped
    # Volumes para desenvolvimento ao vivo (templates, código, etc.)
    volumes:
      - ./MVC_sistema_leitura_hidrometros:/app/MVC_sistema_leitura_hidrometros

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hidrometro
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mosquitto_data:
  mosquitto_log:
  pgdata:
# Arquivo adaptado para remover backend Node legado e adicionar serviço Flask
