services:
  backend:
    build: .
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - PORT=${PORT:-3000}
      - MQTT_URL=${MQTT_URL:-mqtt://mosquitto:1883}
      - MQTT_TOPIC=${MQTT_TOPIC:-hidrometro/leandro/dados}
      - MQTT_CMD_TOPIC=${MQTT_CMD_TOPIC:-hidrometro/leandro/cmd}
    volumes:
      - ./backend/data:/app/backend/data
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
